version: '3'

services:
  main:
    build: main
    ports:
      - "30025:30025"
    restart: always
    command: npm start
    volumes:
      - ./main/:/usr/src/elf-main
      - /usr/src/elf-main/node_modules/
  route-tester:
    build: route-tester
    ports:
      - "30029:30029"
    restart: always
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - ./route-tester/:/usr/src/route-tester
      - /usr/src/route-tester/node_modules/
  system-environment:
    build: system-environment
    ports:
      - "30028:30028"
    restart: always
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - ./system-environment/:/usr/src/system-environment
      - /usr/src/system-environment/node_modules/
